/* ============================================================
   SLOVKO — datový soubor (obsah aplikace)
   Jazyky: japonština (ja), angličtina (en), čeština (cs)
   ============================================================ */

const LANGS = {
  ja: { code:"ja", name:"Japonština", native:"日本語", flag:"🇯🇵", tts:"ja-JP", color:"#ef4444" },
  en: { code:"en", name:"Angličtina", native:"English", flag:"🇬🇧", tts:"en-GB", color:"#3b82f6" },
  cs: { code:"cs", name:"Čeština",    native:"Čeština", flag:"🇨🇿", tts:"cs-CZ", color:"#f59e0b" }
};

/* Každé slovo: cs = česky, en = anglicky, ja = japonsky (kana/kanji), romaji = čtení.
   noType:true u jednotky = vynechá psaní celých vět (frázový trénink). */
const UNITS = [
  { id:"basics", name:"Základy", ico:"👋", color:"#6c5ce7", words:[
    { id:"b1",  cs:"ahoj",        en:"hello",        ja:"こんにちは",     romaji:"konnichiwa", ico:"👋" },
    { id:"b2",  cs:"sbohem",      en:"goodbye",      ja:"さようなら",     romaji:"sayounara",  ico:"🚪" },
    { id:"b3",  cs:"ano",         en:"yes",          ja:"はい",           romaji:"hai",        ico:"✅" },
    { id:"b4",  cs:"ne",          en:"no",           ja:"いいえ",         romaji:"iie",        ico:"❌" },
    { id:"b5",  cs:"prosím",      en:"please",       ja:"おねがいします", romaji:"onegaishimasu", ico:"🙏" },
    { id:"b6",  cs:"děkuji",      en:"thank you",    ja:"ありがとう",     romaji:"arigatou",   ico:"💖" },
    { id:"b7",  cs:"promiň",      en:"sorry",        ja:"ごめんなさい",   romaji:"gomennasai", ico:"😅" },
    { id:"b8",  cs:"dobré ráno",  en:"good morning", ja:"おはよう",       romaji:"ohayou",     ico:"🌅" },
    { id:"b9",  cs:"dobrou noc",  en:"good night",   ja:"おやすみなさい", romaji:"oyasuminasai", ico:"🌙" },
    { id:"b10", cs:"dobrý",       en:"good",         ja:"いい",           romaji:"ii",         ico:"👍" },
    { id:"b11", cs:"špatný",      en:"bad",          ja:"わるい",         romaji:"warui",      ico:"👎" },
    { id:"b12", cs:"jak se máš",  en:"how are you",  ja:"げんきですか",   romaji:"genki desu ka", ico:"💬" }
  ]},
  { id:"numbers", name:"Čísla", ico:"🔢", color:"#0984e3", words:[
    { id:"n1",  cs:"jedna",      en:"one",       ja:"いち",   romaji:"ichi",  ico:"1️⃣" },
    { id:"n2",  cs:"dva",        en:"two",       ja:"に",     romaji:"ni",    ico:"2️⃣" },
    { id:"n3",  cs:"tři",        en:"three",     ja:"さん",   romaji:"san",   ico:"3️⃣" },
    { id:"n4",  cs:"čtyři",      en:"four",      ja:"よん",   romaji:"yon",   ico:"4️⃣" },
    { id:"n5",  cs:"pět",        en:"five",      ja:"ご",     romaji:"go",    ico:"5️⃣" },
    { id:"n6",  cs:"šest",       en:"six",       ja:"ろく",   romaji:"roku",  ico:"6️⃣" },
    { id:"n7",  cs:"sedm",       en:"seven",     ja:"なな",   romaji:"nana",  ico:"7️⃣" },
    { id:"n8",  cs:"osm",        en:"eight",     ja:"はち",   romaji:"hachi", ico:"8️⃣" },
    { id:"n9",  cs:"devět",      en:"nine",      ja:"きゅう", romaji:"kyuu",  ico:"9️⃣" },
    { id:"n10", cs:"deset",      en:"ten",       ja:"じゅう", romaji:"juu",   ico:"🔟" },
    { id:"n11", cs:"dvacet",     en:"twenty",    ja:"にじゅう", romaji:"nijuu", ico:"💯" },
    { id:"n12", cs:"sto",        en:"hundred",   ja:"ひゃく", romaji:"hyaku", ico:"💯" },
    { id:"n13", cs:"tisíc",      en:"thousand",  ja:"せん",   romaji:"sen",    ico:"💸" },
    { id:"n14", cs:"milion",     en:"million",   ja:"ひゃくまん", romaji:"hyakuman", ico:"🤑" }
  ]},
  { id:"kana", name:"Japonská abeceda", ico:"あ", color:"#e84393", kana:true, words:[
    { id:"k1",  cs:"a",  en:"a",  ja:"あ", romaji:"a",  ico:"あ" },
    { id:"k2",  cs:"i",  en:"i",  ja:"い", romaji:"i",  ico:"い" },
    { id:"k3",  cs:"u",  en:"u",  ja:"う", romaji:"u",  ico:"う" },
    { id:"k4",  cs:"e",  en:"e",  ja:"え", romaji:"e",  ico:"え" },
    { id:"k5",  cs:"o",  en:"o",  ja:"お", romaji:"o",  ico:"お" },
    { id:"k6",  cs:"ka", en:"ka", ja:"か", romaji:"ka", ico:"か" },
    { id:"k7",  cs:"ki", en:"ki", ja:"き", romaji:"ki", ico:"き" },
    { id:"k8",  cs:"ku", en:"ku", ja:"く", romaji:"ku", ico:"く" },
    { id:"k9",  cs:"ke", en:"ke", ja:"け", romaji:"ke", ico:"け" },
    { id:"k10", cs:"ko", en:"ko", ja:"こ", romaji:"ko", ico:"こ" },
    { id:"k11", cs:"sa", en:"sa", ja:"さ", romaji:"sa", ico:"さ" },
    { id:"k12", cs:"shi", en:"shi", ja:"し", romaji:"shi", ico:"し" },
    { id:"k13", cs:"su", en:"su", ja:"す", romaji:"su", ico:"す" },
    { id:"k14", cs:"se", en:"se", ja:"せ", romaji:"se", ico:"せ" },
    { id:"k15", cs:"so", en:"so", ja:"そ", romaji:"so", ico:"そ" },
    { id:"k16", cs:"ta", en:"ta", ja:"た", romaji:"ta", ico:"た" },
    { id:"k17", cs:"chi", en:"chi", ja:"ち", romaji:"chi", ico:"ち" },
    { id:"k18", cs:"tsu", en:"tsu", ja:"つ", romaji:"tsu", ico:"つ" },
    { id:"k19", cs:"te", en:"te", ja:"て", romaji:"te", ico:"て" },
    { id:"k20", cs:"to", en:"to", ja:"と", romaji:"to", ico:"と" },
    { id:"k21", cs:"na", en:"na", ja:"な", romaji:"na", ico:"な" },
    { id:"k22", cs:"ni", en:"ni", ja:"に", romaji:"ni", ico:"に" },
    { id:"k23", cs:"nu", en:"nu", ja:"ぬ", romaji:"nu", ico:"ぬ" },
    { id:"k24", cs:"ne", en:"ne", ja:"ね", romaji:"ne", ico:"ね" },
    { id:"k25", cs:"no", en:"no", ja:"の", romaji:"no", ico:"の" },
    { id:"k26", cs:"ha", en:"ha", ja:"は", romaji:"ha", ico:"は" },
    { id:"k27", cs:"hi", en:"hi", ja:"ひ", romaji:"hi", ico:"ひ" },
    { id:"k28", cs:"fu", en:"fu", ja:"ふ", romaji:"fu", ico:"ふ" },
    { id:"k29", cs:"he", en:"he", ja:"へ", romaji:"he", ico:"へ" },
    { id:"k30", cs:"ho", en:"ho", ja:"ほ", romaji:"ho", ico:"ほ" },
    { id:"k31", cs:"ma", en:"ma", ja:"ま", romaji:"ma", ico:"ま" },
    { id:"k32", cs:"mi", en:"mi", ja:"み", romaji:"mi", ico:"み" },
    { id:"k33", cs:"mu", en:"mu", ja:"む", romaji:"mu", ico:"む" },
    { id:"k34", cs:"me", en:"me", ja:"め", romaji:"me", ico:"め" },
    { id:"k35", cs:"mo", en:"mo", ja:"も", romaji:"mo", ico:"も" },
    { id:"k36", cs:"ya", en:"ya", ja:"や", romaji:"ya", ico:"や" },
    { id:"k37", cs:"yu", en:"yu", ja:"ゆ", romaji:"yu", ico:"ゆ" },
    { id:"k38", cs:"yo", en:"yo", ja:"よ", romaji:"yo", ico:"よ" },
    { id:"k39", cs:"ra", en:"ra", ja:"ら", romaji:"ra", ico:"ら" },
    { id:"k40", cs:"ri", en:"ri", ja:"り", romaji:"ri", ico:"り" },
    { id:"k41", cs:"ru", en:"ru", ja:"る", romaji:"ru", ico:"る" },
    { id:"k42", cs:"re", en:"re", ja:"れ", romaji:"re", ico:"れ" },
    { id:"k43", cs:"ro", en:"ro", ja:"ろ", romaji:"ro", ico:"ろ" },
    { id:"k44", cs:"wa", en:"wa", ja:"わ", romaji:"wa", ico:"わ" },
    { id:"k45", cs:"wo", en:"wo", ja:"を", romaji:"wo", ico:"を" },
    { id:"k46", cs:"n",  en:"n",  ja:"ん", romaji:"n",  ico:"ん" }
  ]},
  { id:"food", name:"Jídlo a pití", ico:"🍎", color:"#e17055", words:[
    { id:"f1",  cs:"jablko",     en:"apple",     ja:"りんご",     romaji:"ringo",   ico:"🍎" },
    { id:"f2",  cs:"chléb",      en:"bread",     ja:"パン",       romaji:"pan",     ico:"🍞" },
    { id:"f3",  cs:"voda",       en:"water",     ja:"みず",       romaji:"mizu",    ico:"💧" },
    { id:"f4",  cs:"rýže",       en:"rice",      ja:"ごはん",     romaji:"gohan",   ico:"🍚" },
    { id:"f5",  cs:"ryba",       en:"fish",      ja:"さかな",     romaji:"sakana",  ico:"🐟" },
    { id:"f6",  cs:"maso",       en:"meat",      ja:"にく",       romaji:"niku",    ico:"🥩" },
    { id:"f7",  cs:"mléko",      en:"milk",      ja:"ぎゅうにゅう", romaji:"gyuunyuu", ico:"🥛" },
    { id:"f8",  cs:"vejce",      en:"egg",       ja:"たまご",     romaji:"tamago",  ico:"🥚" },
    { id:"f9",  cs:"čaj",        en:"tea",       ja:"おちゃ",     romaji:"ocha",    ico:"🍵" },
    { id:"f10", cs:"káva",       en:"coffee",    ja:"コーヒー",   romaji:"koohii",  ico:"☕" },
    { id:"f11", cs:"cukr",       en:"sugar",     ja:"さとう",     romaji:"satou",   ico:"🍬" },
    { id:"f12", cs:"sůl",        en:"salt",      ja:"しお",       romaji:"shio",    ico:"🧂" },
    { id:"f13", cs:"kuře",       en:"chicken",   ja:"とりにく",   romaji:"toriniku", ico:"🍗" },
    { id:"f14", cs:"polévka",    en:"soup",      ja:"みそしる",   romaji:"misoshiru", ico:"🍜" },
    { id:"f15", cs:"zelenina",   en:"vegetable", ja:"やさい",     romaji:"yasai",   ico:"🥦" },
    { id:"f16", cs:"ovoce",      en:"fruit",     ja:"くだもの",   romaji:"kudamono", ico:"🍇" }
  ]},
  { id:"animals", name:"Zvířata", ico:"🐶", color:"#00b894", words:[
    { id:"a1",  cs:"pes",        en:"dog",       ja:"いぬ",     romaji:"inu",     ico:"🐶" },
    { id:"a2",  cs:"kočka",      en:"cat",       ja:"ねこ",     romaji:"neko",    ico:"🐱" },
    { id:"a3",  cs:"pták",       en:"bird",      ja:"とり",     romaji:"tori",    ico:"🐦" },
    { id:"a4",  cs:"kůň",        en:"horse",     ja:"うま",     romaji:"uma",     ico:"🐴" },
    { id:"a5",  cs:"medvěd",     en:"bear",      ja:"くま",     romaji:"kuma",    ico:"🐻" },
    { id:"a6",  cs:"myš",        en:"mouse",     ja:"ねずみ",   romaji:"nezumi",  ico:"🐭" },
    { id:"a7",  cs:"králík",     en:"rabbit",    ja:"うさぎ",   romaji:"usagi",   ico:"🐰" },
    { id:"a8",  cs:"kráva",      en:"cow",       ja:"うし",     romaji:"ushi",    ico:"🐮" },
    { id:"a9",  cs:"prase",      en:"pig",       ja:"ぶた",     romaji:"buta",    ico:"🐷" },
    { id:"a10", cs:"ovce",       en:"sheep",     ja:"ひつじ",   romaji:"hitsuji", ico:"🐑" },
    { id:"a11", cs:"lev",        en:"lion",      ja:"ライオン", romaji:"raion",   ico:"🦁" },
    { id:"a12", cs:"opice",      en:"monkey",    ja:"さる",     romaji:"saru",    ico:"🐵" },
    { id:"a13", cs:"slon",       en:"elephant",  ja:"ぞう",     romaji:"zou",     ico:"🐘" },
    { id:"a14", cs:"želva",      en:"turtle",    ja:"かめ",     romaji:"kame",    ico:"🐢" }
  ]},
  { id:"colors", name:"Barvy", ico:"🎨", color:"#a29bfe", words:[
    { id:"c1",  cs:"červená",    en:"red",       ja:"あか",     romaji:"aka",     ico:"🔴" },
    { id:"c2",  cs:"modrá",      en:"blue",      ja:"あお",     romaji:"ao",      ico:"🔵" },
    { id:"c3",  cs:"zelená",     en:"green",     ja:"みどり",   romaji:"midori",  ico:"🟢" },
    { id:"c4",  cs:"žlutá",      en:"yellow",    ja:"きいろ",   romaji:"kiiro",   ico:"🟡" },
    { id:"c5",  cs:"černá",      en:"black",     ja:"くろ",     romaji:"kuro",    ico:"⚫" },
    { id:"c6",  cs:"bílá",       en:"white",     ja:"しろ",     romaji:"shiro",   ico:"⚪" },
    { id:"c7",  cs:"oranžová",   en:"orange",    ja:"オレンジ", romaji:"orenji",  ico:"🟠" },
    { id:"c8",  cs:"růžová",     en:"pink",      ja:"ピンク",   romaji:"pinku",   ico:"🌸" },
    { id:"c9",  cs:"fialová",    en:"purple",    ja:"むらさき", romaji:"murasaki", ico:"🟣" },
    { id:"c10", cs:"hnědá",      en:"brown",     ja:"ちゃいろ", romaji:"chairo",  ico:"🟤" },
    { id:"c11", cs:"šedá",       en:"gray",      ja:"はいいろ", romaji:"haiiro",  ico:"⚪" },
    { id:"c12", cs:"zlatá",      en:"gold",      ja:"きんいろ", romaji:"kin'iro", ico:"🟡" }
  ]},
  { id:"family", name:"Rodina", ico:"👨‍👩‍👧", color:"#fd79a8", words:[
    { id:"m1",  cs:"matka",      en:"mother",     ja:"おかあさん", romaji:"okaasan", ico:"👩" },
    { id:"m2",  cs:"otec",       en:"father",     ja:"おとうさん", romaji:"otousan", ico:"👨" },
    { id:"m3",  cs:"bratr",      en:"brother",    ja:"あに",       romaji:"ani",     ico:"👦" },
    { id:"m4",  cs:"sestra",     en:"sister",     ja:"あね",       romaji:"ane",     ico:"👧" },
    { id:"m5",  cs:"babička",    en:"grandmother", ja:"おばあさん", romaji:"obaasan", ico:"👵" },
    { id:"m6",  cs:"dědeček",    en:"grandfather", ja:"おじいさん", romaji:"ojiisan", ico:"👴" },
    { id:"m7",  cs:"syn",        en:"son",        ja:"むすこ",     romaji:"musuko",  ico:"👶" },
    { id:"m8",  cs:"dcera",      en:"daughter",   ja:"むすめ",     romaji:"musume",  ico:"👧" },
    { id:"m9",  cs:"rodina",     en:"family",     ja:"かぞく",     romaji:"kazoku",  ico:"👨‍👩‍👧" },
    { id:"m10", cs:"dítě",       en:"child",      ja:"こども",     romaji:"kodomo",  ico:"🧒" },
    { id:"m11", cs:"manžel",     en:"husband",    ja:"おっと",     romaji:"otto",    ico:"💍" },
    { id:"m12", cs:"manželka",   en:"wife",       ja:"つま",       romaji:"tsuma",   ico:"💍" }
  ]},
  { id:"body", name:"Tělo a zdraví", ico:"💪", color:"#fab1a0", words:[
    { id:"bo1", cs:"hlava",      en:"head",       ja:"あたま",   romaji:"atama",    ico:"🗣️" },
    { id:"bo2", cs:"oko",        en:"eye",        ja:"め",       romaji:"me",       ico:"👁️" },
    { id:"bo3", cs:"ucho",       en:"ear",        ja:"みみ",     romaji:"mimi",     ico:"👂" },
    { id:"bo4", cs:"nos",        en:"nose",       ja:"はな",     romaji:"hana",     ico:"👃" },
    { id:"bo5", cs:"ústa",       en:"mouth",      ja:"くち",     romaji:"kuchi",    ico:"👄" },
    { id:"bo6", cs:"ruka",       en:"hand",       ja:"て",       romaji:"te",       ico:"✋" },
    { id:"bo7", cs:"noha",       en:"foot",       ja:"あし",     romaji:"ashi",     ico:"🦶" },
    { id:"bo8", cs:"srdce",      en:"heart",      ja:"しんぞう", romaji:"shinzou",  ico:"💓" },
    { id:"bo9", cs:"doktor",     en:"doctor",     ja:"いしゃ",   romaji:"isha",     ico:"🧑‍⚕️" },
    { id:"bo10",cs:"nemocný",    en:"sick",       ja:"びょうき", romaji:"byouki",   ico:"🤒" },
    { id:"bo11",cs:"bolest",     en:"pain",       ja:"いたみ",   romaji:"itami",    ico:"😖" },
    { id:"bo12",cs:"lék",        en:"medicine",   ja:"くすり",   romaji:"kusuri",   ico:"💊" },
    { id:"bo13",cs:"zub",        en:"tooth",      ja:"は",       romaji:"ha",       ico:"🦷" },
    { id:"bo14",cs:"záda",       en:"back",       ja:"せなか",   romaji:"senaka",   ico:"🔙" }
  ]},
  { id:"clothes", name:"Oblečení", ico:"👕", color:"#74b9ff", words:[
    { id:"cl1", cs:"košile",     en:"shirt",      ja:"シャツ",     romaji:"shatsu",   ico:"👕" },
    { id:"cl2", cs:"kalhoty",    en:"trousers",   ja:"ズボン",     romaji:"zubon",    ico:"👖" },
    { id:"cl3", cs:"boty",       en:"shoes",      ja:"くつ",       romaji:"kutsu",    ico:"👟" },
    { id:"cl4", cs:"bunda",      en:"jacket",     ja:"うわぎ",     romaji:"uwagi",    ico:"🧥" },
    { id:"cl5", cs:"klobouk",    en:"hat",        ja:"ぼうし",     romaji:"boushi",   ico:"🎩" },
    { id:"cl6", cs:"šaty",       en:"dress",      ja:"ワンピース", romaji:"wanpiisu", ico:"👗" },
    { id:"cl7", cs:"ponožky",    en:"socks",      ja:"くつした",   romaji:"kutsushita", ico:"🧦" },
    { id:"cl8", cs:"kabát",      en:"coat",       ja:"コート",     romaji:"kooto",    ico:"🧥" },
    { id:"cl9", cs:"šála",       en:"scarf",      ja:"マフラー",   romaji:"mafuraa",  ico:"🧣" },
    { id:"cl10",cs:"brýle",      en:"glasses",    ja:"めがね",     romaji:"megane",   ico:"👓" },
    { id:"cl11",cs:"rukavice",   en:"gloves",     ja:"てぶくろ",   romaji:"tebukuro", ico:"🧤" },
    { id:"cl12",cs:"sukně",      en:"skirt",      ja:"スカート",   romaji:"sukaato",  ico:"👗" }
  ]},
  { id:"home", name:"Domov", ico:"🏠", color:"#fdcb6e", words:[
    { id:"ho1", cs:"dům",        en:"house",      ja:"いえ",       romaji:"ie",       ico:"🏠" },
    { id:"ho2", cs:"pokoj",      en:"room",       ja:"へや",       romaji:"heya",     ico:"🚪" },
    { id:"ho3", cs:"kuchyně",    en:"kitchen",    ja:"だいどころ", romaji:"daidokoro", ico:"🍳" },
    { id:"ho4", cs:"ložnice",    en:"bedroom",    ja:"しんしつ",   romaji:"shinshitsu", ico:"🛏️" },
    { id:"ho5", cs:"koupelna",   en:"bathroom",   ja:"よくしつ",   romaji:"yokushitsu", ico:"🛁" },
    { id:"ho6", cs:"dveře",      en:"door",       ja:"ドア",       romaji:"doa",      ico:"🚪" },
    { id:"ho7", cs:"okno",       en:"window",     ja:"まど",       romaji:"mado",     ico:"🪟" },
    { id:"ho8", cs:"stůl",       en:"table",      ja:"テーブル",   romaji:"teeburu",  ico:"🪑" },
    { id:"ho9", cs:"židle",      en:"chair",      ja:"いす",       romaji:"isu",      ico:"🪑" },
    { id:"ho10",cs:"postel",     en:"bed",        ja:"ベッド",     romaji:"beddo",    ico:"🛏️" },
    { id:"ho11",cs:"klíč",       en:"key",        ja:"かぎ",       romaji:"kagi",     ico:"🔑" },
    { id:"ho12",cs:"lednice",    en:"fridge",     ja:"れいぞうこ", romaji:"reizouko", ico:"🧊" },
    { id:"ho13",cs:"zahrada",    en:"garden",     ja:"にわ",       romaji:"niwa",     ico:"🌳" }
  ]},
  { id:"city", name:"Město", ico:"🏙️", color:"#0984e3", words:[
    { id:"ci1", cs:"město",      en:"city",       ja:"まち",       romaji:"machi",    ico:"🏙️" },
    { id:"ci2", cs:"banka",      en:"bank",       ja:"ぎんこう",   romaji:"ginkou",   ico:"🏦" },
    { id:"ci3", cs:"nemocnice",  en:"hospital",   ja:"びょういん", romaji:"byouin",   ico:"🏥" },
    { id:"ci4", cs:"škola",      en:"school",     ja:"がっこう",   romaji:"gakkou",   ico:"🏫" },
    { id:"ci5", cs:"obchod",     en:"shop",       ja:"みせ",       romaji:"mise",     ico:"🏪" },
    { id:"ci6", cs:"restaurace", en:"restaurant", ja:"レストラン", romaji:"resutoran", ico:"🍽️" },
    { id:"ci7", cs:"lékárna",    en:"pharmacy",   ja:"くすりや",   romaji:"kusuriya", ico:"💊" },
    { id:"ci8", cs:"park",       en:"park",       ja:"こうえん",   romaji:"kouen",    ico:"🌲" },
    { id:"ci9", cs:"most",       en:"bridge",     ja:"はし",       romaji:"hashi",    ico:"🌉" },
    { id:"ci10",cs:"kino",       en:"cinema",     ja:"えいがかん", romaji:"eigakan",  ico:"🎬" },
    { id:"ci11",cs:"náměstí",    en:"square",     ja:"ひろば",     romaji:"hiroba",   ico:"🏛️" },
    { id:"ci12",cs:"pošta",      en:"post office",ja:"ゆうびんきょく", romaji:"yuubinkyoku", ico:"📮" }
  ]},
  { id:"travel", name:"Cestování", ico:"✈️", color:"#74b9ff", words:[
    { id:"r1",  cs:"vlak",       en:"train",     ja:"でんしゃ", romaji:"densha",  ico:"🚆" },
    { id:"r2",  cs:"autobus",    en:"bus",       ja:"バス",     romaji:"basu",    ico:"🚌" },
    { id:"r3",  cs:"letadlo",    en:"plane",     ja:"ひこうき", romaji:"hikouki", ico:"✈️" },
    { id:"r4",  cs:"auto",       en:"car",       ja:"くるま",   romaji:"kuruma",  ico:"🚗" },
    { id:"r5",  cs:"jízdenka",   en:"ticket",    ja:"きっぷ",   romaji:"kippu",   ico:"🎫" },
    { id:"r6",  cs:"hotel",      en:"hotel",     ja:"ホテル",   romaji:"hoteru",  ico:"🏨" },
    { id:"r7",  cs:"letiště",    en:"airport",   ja:"くうこう", romaji:"kuukou",  ico:"🛫" },
    { id:"r8",  cs:"nádraží",    en:"station",   ja:"えき",     romaji:"eki",     ico:"🚉" },
    { id:"r9",  cs:"ulice",      en:"street",    ja:"みち",     romaji:"michi",   ico:"🛣️" },
    { id:"r10", cs:"mapa",       en:"map",       ja:"ちず",     romaji:"chizu",   ico:"🗺️" },
    { id:"r11", cs:"pas",        en:"passport",  ja:"パスポート", romaji:"pasupooto", ico:"🛂" },
    { id:"r12", cs:"zavazadlo",  en:"luggage",   ja:"にもつ",   romaji:"nimotsu", ico:"🧳" },
    { id:"r13", cs:"taxi",       en:"taxi",      ja:"タクシー", romaji:"takushii", ico:"🚕" }
  ]},
  { id:"shopping", name:"Nakupování", ico:"🛒", color:"#55efc4", words:[
    { id:"sh1", cs:"peníze",     en:"money",      ja:"おかね",     romaji:"okane",     ico:"💰" },
    { id:"sh2", cs:"cena",       en:"price",      ja:"ねだん",     romaji:"nedan",     ico:"🏷️" },
    { id:"sh3", cs:"platit",     en:"to pay",     ja:"はらう",     romaji:"harau",     ico:"💳" },
    { id:"sh4", cs:"levný",      en:"cheap",      ja:"やすい",     romaji:"yasui",     ico:"💸" },
    { id:"sh5", cs:"drahý",      en:"expensive",  ja:"たかい",     romaji:"takai",     ico:"💎" },
    { id:"sh6", cs:"koupit",     en:"to buy",     ja:"かう",       romaji:"kau",       ico:"🛍️" },
    { id:"sh7", cs:"prodat",     en:"to sell",    ja:"うる",       romaji:"uru",       ico:"🏪" },
    { id:"sh8", cs:"peněženka",  en:"wallet",     ja:"さいふ",     romaji:"saifu",     ico:"👛" },
    { id:"sh9", cs:"hotovost",   en:"cash",       ja:"げんきん",   romaji:"genkin",    ico:"💵" },
    { id:"sh10",cs:"karta",      en:"card",       ja:"カード",     romaji:"kaado",     ico:"💳" },
    { id:"sh11",cs:"sleva",      en:"discount",   ja:"わりびき",   romaji:"waribiki",  ico:"🏷️" },
    { id:"sh12",cs:"dárek",      en:"gift",       ja:"プレゼント", romaji:"purezento", ico:"🎁" }
  ]},
  { id:"time", name:"Čas", ico:"⏰", color:"#fdcb6e", words:[
    { id:"t1",  cs:"dnes",       en:"today",     ja:"きょう",   romaji:"kyou",     ico:"📅" },
    { id:"t2",  cs:"zítra",      en:"tomorrow",  ja:"あした",   romaji:"ashita",   ico:"🌄" },
    { id:"t3",  cs:"včera",      en:"yesterday", ja:"きのう",   romaji:"kinou",    ico:"🌇" },
    { id:"t4",  cs:"ráno",       en:"morning",   ja:"あさ",     romaji:"asa",      ico:"🌅" },
    { id:"t5",  cs:"večer",      en:"evening",   ja:"ゆうがた", romaji:"yuugata",  ico:"🌆" },
    { id:"t6",  cs:"noc",        en:"night",     ja:"よる",     romaji:"yoru",     ico:"🌃" },
    { id:"t7",  cs:"den",        en:"day",       ja:"ひ",       romaji:"hi",       ico:"☀️" },
    { id:"t8",  cs:"týden",      en:"week",      ja:"しゅう",   romaji:"shuu",     ico:"🗓️" },
    { id:"t9",  cs:"rok",        en:"year",      ja:"とし",     romaji:"toshi",    ico:"🎆" },
    { id:"t10", cs:"hodina",     en:"hour",      ja:"じかん",   romaji:"jikan",    ico:"⏰" },
    { id:"t11", cs:"minuta",     en:"minute",    ja:"ふん",     romaji:"fun",      ico:"⏱️" },
    { id:"t12", cs:"sekunda",    en:"second",    ja:"びょう",   romaji:"byou",     ico:"⚡" }
  ]},
  { id:"days", name:"Dny v týdnu", ico:"📅", color:"#74b9ff", words:[
    { id:"d1",  cs:"pondělí",    en:"Monday",    ja:"げつようび", romaji:"getsuyoubi", ico:"📅" },
    { id:"d2",  cs:"úterý",      en:"Tuesday",   ja:"かようび",   romaji:"kayoubi",    ico:"📅" },
    { id:"d3",  cs:"středa",     en:"Wednesday", ja:"すいようび", romaji:"suiyoubi",   ico:"📅" },
    { id:"d4",  cs:"čtvrtek",    en:"Thursday",  ja:"もくようび", romaji:"mokuyoubi",  ico:"📅" },
    { id:"d5",  cs:"pátek",      en:"Friday",    ja:"きんようび", romaji:"kinyoubi",   ico:"📅" },
    { id:"d6",  cs:"sobota",     en:"Saturday",  ja:"どようび",   romaji:"doyoubi",    ico:"📅" },
    { id:"d7",  cs:"neděle",     en:"Sunday",    ja:"にちようび", romaji:"nichiyoubi", ico:"📅" },
    { id:"d8",  cs:"víkend",     en:"weekend",   ja:"しゅうまつ", romaji:"shuumatsu",  ico:"🌴" },
    { id:"d9",  cs:"každý den",  en:"every day", ja:"まいにち",   romaji:"mainichi",   ico:"🔁" }
  ]},
  { id:"months", name:"Měsíce a roční období", ico:"🗓️", color:"#a29bfe", words:[
    { id:"mo1",  cs:"leden",     en:"January",   ja:"いちがつ", romaji:"ichigatsu",   ico:"❄️" },
    { id:"mo2",  cs:"únor",      en:"February",  ja:"にがつ",   romaji:"nigatsu",    ico:"❄️" },
    { id:"mo3",  cs:"březen",    en:"March",     ja:"さんがつ", romaji:"sangatsu",   ico:"🌸" },
    { id:"mo4",  cs:"duben",     en:"April",     ja:"しがつ",   romaji:"shigatsu",   ico:"🌸" },
    { id:"mo5",  cs:"květen",    en:"May",       ja:"ごがつ",   romaji:"gogatsu",    ico:"🌼" },
    { id:"mo6",  cs:"červen",    en:"June",      ja:"ろくがつ", romaji:"rokugatsu",  ico:"☀️" },
    { id:"mo7",  cs:"červenec",  en:"July",      ja:"しちがつ", romaji:"shichigatsu", ico:"☀️" },
    { id:"mo8",  cs:"srpen",     en:"August",    ja:"はちがつ", romaji:"hachigatsu", ico:"🌻" },
    { id:"mo9",  cs:"září",      en:"September", ja:"くがつ",   romaji:"kugatsu",    ico:"🍂" },
    { id:"mo10", cs:"říjen",     en:"October",   ja:"じゅうがつ", romaji:"juugatsu",  ico:"🍂" },
    { id:"mo11", cs:"listopad",  en:"November",  ja:"じゅういちがつ", romaji:"juuichigatsu", ico:"🍁" },
    { id:"mo12", cs:"prosinec",  en:"December",  ja:"じゅうにがつ", romaji:"juunigatsu", ico:"🎄" },
    { id:"mo13", cs:"jaro",      en:"spring",    ja:"はる",     romaji:"haru",       ico:"🌸" },
    { id:"mo14", cs:"léto",      en:"summer",    ja:"なつ",     romaji:"natsu",      ico:"☀️" },
    { id:"mo15", cs:"podzim",    en:"autumn",    ja:"あき",     romaji:"aki",        ico:"🍂" },
    { id:"mo16", cs:"zima",      en:"winter",    ja:"ふゆ",     romaji:"fuyu",       ico:"❄️" }
  ]},
  { id:"weather", name:"Počasí", ico:"🌦️", color:"#00cec9", words:[
    { id:"we1", cs:"počasí",     en:"weather",   ja:"てんき",   romaji:"tenki",    ico:"🌤️" },
    { id:"we2", cs:"horko",      en:"hot",       ja:"あつい",   romaji:"atsui",    ico:"🥵" },
    { id:"we3", cs:"studený",    en:"cold",      ja:"さむい",   romaji:"samui",    ico:"🥶" },
    { id:"we4", cs:"teplo",      en:"warm",      ja:"あたたかい", romaji:"atatakai", ico:"🌡️" },
    { id:"we5", cs:"chladno",    en:"cool",      ja:"すずしい", romaji:"suzushii", ico:"🍃" },
    { id:"we6", cs:"slunečno",   en:"sunny",     ja:"はれ",     romaji:"hare",     ico:"☀️" },
    { id:"we7", cs:"zataženo",   en:"cloudy",    ja:"くもり",   romaji:"kumori",   ico:"☁️" },
    { id:"we8", cs:"bouřka",     en:"storm",     ja:"あらし",   romaji:"arashi",   ico:"⛈️" },
    { id:"we9", cs:"mlha",       en:"fog",       ja:"きり",     romaji:"kiri",     ico:"🌫️" },
    { id:"we10",cs:"duha",       en:"rainbow",   ja:"にじ",     romaji:"niji",     ico:"🌈" },
    { id:"we11",cs:"oblak",      en:"cloud",     ja:"くも",     romaji:"kumo",     ico:"☁️" },
    { id:"we12",cs:"vlhko",      en:"humid",     ja:"しめった", romaji:"shimetta", ico:"💧" }
  ]},
  { id:"nature", name:"Příroda", ico:"🌳", color:"#55efc4", words:[
    { id:"p1",  cs:"slunce",     en:"sun",       ja:"たいよう", romaji:"taiyou",  ico:"🌞" },
    { id:"p2",  cs:"měsíc",      en:"moon",      ja:"つき",     romaji:"tsuki",   ico:"🌙" },
    { id:"p3",  cs:"hvězda",     en:"star",      ja:"ほし",     romaji:"hoshi",   ico:"⭐" },
    { id:"p4",  cs:"nebe",       en:"sky",       ja:"そら",     romaji:"sora",    ico:"🌌" },
    { id:"p5",  cs:"moře",       en:"sea",       ja:"うみ",     romaji:"umi",     ico:"🌊" },
    { id:"p6",  cs:"hora",       en:"mountain",  ja:"やま",     romaji:"yama",    ico:"⛰️" },
    { id:"p7",  cs:"řeka",       en:"river",     ja:"かわ",     romaji:"kawa",    ico:"🏞️" },
    { id:"p8",  cs:"strom",      en:"tree",      ja:"き",       romaji:"ki",      ico:"🌳" },
    { id:"p9",  cs:"květina",    en:"flower",    ja:"はな",     romaji:"hana",    ico:"🌸" },
    { id:"p10", cs:"déšť",       en:"rain",      ja:"あめ",     romaji:"ame",     ico:"🌧️" },
    { id:"p11", cs:"sníh",       en:"snow",      ja:"ゆき",     romaji:"yuki",    ico:"❄️" },
    { id:"p12", cs:"vítr",       en:"wind",      ja:"かぜ",     romaji:"kaze",    ico:"💨" },
    { id:"p13", cs:"les",        en:"forest",    ja:"もり",     romaji:"mori",    ico:"🌲" },
    { id:"p14", cs:"ostrov",     en:"island",    ja:"しま",     romaji:"shima",   ico:"🏝️" }
  ]},
  { id:"verbs", name:"Slovesa", ico:"🏃", color:"#00cec9", words:[
    { id:"v1",  cs:"jíst",       en:"to eat",    ja:"たべる",   romaji:"taberu",  ico:"🍽️" },
    { id:"v2",  cs:"pít",        en:"to drink",  ja:"のむ",     romaji:"nomu",    ico:"🥤" },
    { id:"v3",  cs:"vidět",      en:"to see",    ja:"みる",     romaji:"miru",    ico:"👀" },
    { id:"v4",  cs:"jít",        en:"to go",     ja:"いく",     romaji:"iku",     ico:"🚶" },
    { id:"v5",  cs:"mluvit",     en:"to speak",  ja:"はなす",   romaji:"hanasu",  ico:"🗣️" },
    { id:"v6",  cs:"běžet",      en:"to run",    ja:"はしる",   romaji:"hashiru", ico:"🏃" },
    { id:"v7",  cs:"spát",       en:"to sleep",  ja:"ねる",     romaji:"neru",    ico:"😴" },
    { id:"v8",  cs:"číst",       en:"to read",   ja:"よむ",     romaji:"yomu",    ico:"📖" },
    { id:"v9",  cs:"psát",       en:"to write",  ja:"かく",     romaji:"kaku",    ico:"✍️" },
    { id:"v10", cs:"poslouchat", en:"to listen", ja:"きく",     romaji:"kiku",    ico:"👂" },
    { id:"v11", cs:"hrát si",    en:"to play",   ja:"あそぶ",   romaji:"asobu",   ico:"🎮" },
    { id:"v12", cs:"sedět",      en:"to sit",    ja:"すわる",   romaji:"suwaru",  ico:"🪑" },
    { id:"v13", cs:"stát",       en:"to stand",  ja:"たつ",     romaji:"tatsu",   ico:"🧍" }
  ]},
  { id:"verbs2", name:"Slovesa 2", ico:"💪", color:"#6c5ce7", words:[
    { id:"v21", cs:"chtít",      en:"to want",    ja:"ほしい",   romaji:"hoshii",   ico:"🤲" },
    { id:"v22", cs:"potřebovat", en:"to need",    ja:"ひつよう", romaji:"hitsuyou", ico:"❗" },
    { id:"v23", cs:"vědět",      en:"to know",    ja:"しる",     romaji:"shiru",    ico:"🧠" },
    { id:"v24", cs:"rozumět",    en:"to understand", ja:"わかる", romaji:"wakaru",  ico:"💡" },
    { id:"v25", cs:"pomoct",     en:"to help",    ja:"たすける", romaji:"tasukeru", ico:"🤝" },
    { id:"v26", cs:"pracovat",   en:"to work",    ja:"はたらく", romaji:"hataraku", ico:"💼" },
    { id:"v27", cs:"zpívat",     en:"to sing",    ja:"うたう",   romaji:"utau",     ico:"🎤" },
    { id:"v28", cs:"tančit",     en:"to dance",   ja:"おどる",   romaji:"odoru",    ico:"💃" },
    { id:"v29", cs:"bydlet",     en:"to live",    ja:"すむ",     romaji:"sumu",     ico:"🏡" },
    { id:"v210",cs:"vařit",      en:"to cook",    ja:"りょうりする", romaji:"ryouri suru", ico:"🍳" },
    { id:"v211",cs:"učit se",    en:"to learn",   ja:"まなぶ",   romaji:"manabu",   ico:"📚" },
    { id:"v212",cs:"čekat",      en:"to wait",    ja:"まつ",     romaji:"matsu",    ico:"⏳" },
    { id:"v213",cs:"hledat",     en:"to find",    ja:"さがす",   romaji:"sagasu",   ico:"🔍" },
    { id:"v214",cs:"otvírat",    en:"to open",    ja:"あける",   romaji:"akeru",    ico:"🚪" }
  ]},
  { id:"adjectives", name:"Přídavná jména", ico:"✨", color:"#fd79a8", words:[
    { id:"ad1", cs:"velký",      en:"big",        ja:"おおきい", romaji:"ookii",     ico:"🐘" },
    { id:"ad2", cs:"malý",       en:"small",      ja:"ちいさい", romaji:"chiisai",   ico:"🐜" },
    { id:"ad3", cs:"rychlý",     en:"fast",       ja:"はやい",   romaji:"hayai",     ico:"⚡" },
    { id:"ad4", cs:"pomalý",     en:"slow",       ja:"おそい",   romaji:"osoi",      ico:"🐢" },
    { id:"ad5", cs:"nový",       en:"new",        ja:"あたらしい", romaji:"atarashii", ico:"🆕" },
    { id:"ad6", cs:"starý",      en:"old",        ja:"ふるい",   romaji:"furui",     ico:"📜" },
    { id:"ad7", cs:"krásný",     en:"beautiful",  ja:"きれい",   romaji:"kirei",     ico:"🌸" },
    { id:"ad8", cs:"výborný",    en:"delicious",  ja:"おいしい", romaji:"oishii",    ico:"😋" },
    { id:"ad9", cs:"zábavný",    en:"fun",        ja:"たのしい", romaji:"tanoshii",  ico:"🎉" },
    { id:"ad10",cs:"snadný",     en:"easy",       ja:"かんたん", romaji:"kantan",    ico:"🟢" },
    { id:"ad11",cs:"těžký",      en:"difficult",  ja:"むずかしい", romaji:"muzukashii", ico:"🔴" },
    { id:"ad12",cs:"zajímavý",   en:"interesting",ja:"おもしろい", romaji:"omoshiroi", ico:"🤔" }
  ]},
  { id:"feelings", name:"Pocity", ico:"💖", color:"#e84393", words:[
    { id:"fe1", cs:"šťastný",    en:"happy",      ja:"しあわせ", romaji:"shiawase",   ico:"😊" },
    { id:"fe2", cs:"smutný",     en:"sad",        ja:"かなしい", romaji:"kanashii",   ico:"😢" },
    { id:"fe3", cs:"naštvaný",   en:"angry",      ja:"おこっている", romaji:"okotteiru", ico:"😠" },
    { id:"fe4", cs:"unavený",    en:"tired",      ja:"つかれた", romaji:"tsukareta",  ico:"😴" },
    { id:"fe5", cs:"vyděšený",   en:"scared",     ja:"こわい",   romaji:"kowai",      ico:"😱" },
    { id:"fe6", cs:"překvapený", en:"surprised",  ja:"びっくりした", romaji:"bikkuri shita", ico:"😲" },
    { id:"fe7", cs:"láska",      en:"love",       ja:"あい",     romaji:"ai",         ico:"❤️" },
    { id:"fe8", cs:"smát se",    en:"to laugh",   ja:"わらう",   romaji:"warau",      ico:"😂" },
    { id:"fe9", cs:"plakat",     en:"to cry",     ja:"なく",     romaji:"naku",       ico:"😭" },
    { id:"fe10",cs:"nudit se",   en:"bored",      ja:"つまらない", romaji:"tsumaranai", ico:"🥱" },
    { id:"fe11",cs:"nadšený",    en:"excited",    ja:"わくわく", romaji:"wakuwaku",   ico:"🤩" },
    { id:"fe12",cs:"stydlivý",   en:"shy",        ja:"はずかしい", romaji:"hazukashii", ico:"😳" }
  ]},
  { id:"questions", name:"Otázky", ico:"❓", color:"#0984e3", words:[
    { id:"qu1", cs:"kdo",        en:"who",        ja:"だれ",     romaji:"dare",     ico:"🧑" },
    { id:"qu2", cs:"co",         en:"what",       ja:"なに",     romaji:"nani",     ico:"❔" },
    { id:"qu3", cs:"kde",        en:"where",      ja:"どこ",     romaji:"doko",     ico:"📍" },
    { id:"qu4", cs:"kdy",        en:"when",       ja:"いつ",     romaji:"itsu",     ico:"🕐" },
    { id:"qu5", cs:"proč",       en:"why",        ja:"なぜ",     romaji:"naze",     ico:"🤷" },
    { id:"qu6", cs:"jak",        en:"how",        ja:"どう",     romaji:"dou",      ico:"🛠️" },
    { id:"qu7", cs:"kolik",      en:"how much",   ja:"いくら",   romaji:"ikura",    ico:"🔢" },
    { id:"qu8", cs:"který",      en:"which",      ja:"どれ",     romaji:"dore",     ico:"👆" },
    { id:"qu9", cs:"kolik je hodin", en:"what time", ja:"なんじ", romaji:"nanji",   ico:"⏰" }
  ]},
  { id:"pronouns", name:"Zájmena", ico:"👤", color:"#00b894", words:[
    { id:"pr1", cs:"já",         en:"I",          ja:"わたし",   romaji:"watashi",     ico:"🙋" },
    { id:"pr2", cs:"ty",         en:"you",        ja:"あなた",   romaji:"anata",       ico:"👉" },
    { id:"pr3", cs:"on",         en:"he",         ja:"かれ",     romaji:"kare",        ico:"👦" },
    { id:"pr4", cs:"ona",        en:"she",        ja:"かのじょ", romaji:"kanojo",      ico:"👧" },
    { id:"pr5", cs:"my",         en:"we",         ja:"わたしたち", romaji:"watashitachi", ico:"👥" },
    { id:"pr6", cs:"oni",        en:"they",       ja:"かれら",   romaji:"karera",      ico:"👨‍👩‍👧" },
    { id:"pr7", cs:"tohle",      en:"this",       ja:"これ",     romaji:"kore",        ico:"👈" },
    { id:"pr8", cs:"tamto",      en:"that",       ja:"あれ",     romaji:"are",         ico:"👉" },
    { id:"pr9", cs:"tam",        en:"there",      ja:"そこ",     romaji:"soko",        ico:"📍" }
  ]},
  { id:"school", name:"Škola a práce", ico:"💼", color:"#fdcb6e", words:[
    { id:"sc1", cs:"učitel",     en:"teacher",    ja:"せんせい", romaji:"sensei",     ico:"🧑‍🏫" },
    { id:"sc2", cs:"student",    en:"student",    ja:"がくせい", romaji:"gakusei",    ico:"🧑‍🎓" },
    { id:"sc3", cs:"kancelář",   en:"office",     ja:"オフィス", romaji:"ofisu",      ico:"🏢" },
    { id:"sc4", cs:"šéf",        en:"boss",       ja:"じょうし", romaji:"joushi",     ico:"👔" },
    { id:"sc5", cs:"práce",      en:"job",        ja:"しごと",   romaji:"shigoto",    ico:"💼" },
    { id:"sc6", cs:"porada",     en:"meeting",    ja:"かいぎ",   romaji:"kaigi",      ico:"🤝" },
    { id:"sc7", cs:"počítač",    en:"computer",   ja:"コンピューター", romaji:"konpyuutaa", ico:"💻" },
    { id:"sc8", cs:"kniha",      en:"book",       ja:"ほん",     romaji:"hon",        ico:"📖" },
    { id:"sc9", cs:"pero",       en:"pen",        ja:"ペン",     romaji:"pen",        ico:"🖊️" },
    { id:"sc10",cs:"sešit",      en:"notebook",   ja:"ノート",   romaji:"nooto",      ico:"📓" },
    { id:"sc11",cs:"telefon",    en:"phone",      ja:"でんわ",   romaji:"denwa",      ico:"📞" },
    { id:"sc12",cs:"dopis",      en:"letter",     ja:"てがみ",   romaji:"tegami",     ico:"✉️" }
  ]},
  { id:"sports", name:"Sport a zábava", ico:"⚽", color:"#00cec9", words:[
    { id:"sp1", cs:"sport",      en:"sport",      ja:"スポーツ", romaji:"supootsu",  ico:"🏅" },
    { id:"sp2", cs:"hra",        en:"game",       ja:"ゲーム",   romaji:"geemu",     ico:"🎮" },
    { id:"sp3", cs:"hudba",      en:"music",      ja:"おんがく", romaji:"ongaku",    ico:"🎵" },
    { id:"sp4", cs:"film",       en:"movie",      ja:"えいが",   romaji:"eiga",      ico:"🎬" },
    { id:"sp5", cs:"fotbal",     en:"football",   ja:"サッカー", romaji:"sakkaa",    ico:"⚽" },
    { id:"sp6", cs:"plavání",    en:"swimming",   ja:"すいえい", romaji:"suiei",     ico:"🏊" },
    { id:"sp7", cs:"kreslení",   en:"drawing",    ja:"え",       romaji:"e",         ico:"🎨" },
    { id:"sp8", cs:"fotoaparát", en:"camera",     ja:"カメラ",   romaji:"kamera",    ico:"📷" },
    { id:"sp9", cs:"kolo",       en:"bicycle",    ja:"じてんしゃ", romaji:"jitensha",  ico:"🚲" },
    { id:"sp10",cs:"táborák",    en:"camping",    ja:"キャンプ", romaji:"kyanpu",    ico:"🏕️" },
    { id:"sp11",cs:"rybaření",   en:"fishing",    ja:"つり",     romaji:"tsuri",     ico:"🎣" },
    { id:"sp12",cs:"tanec",      en:"dance",      ja:"ダンス",   romaji:"dansu",     ico:"💃" }
  ]},
  { id:"directions", name:"Směry a místa", ico:"🧭", color:"#e17055", words:[
    { id:"di1", cs:"vlevo",      en:"left",       ja:"ひだり",   romaji:"hidari",  ico:"👈" },
    { id:"di2", cs:"vpravo",     en:"right",      ja:"みぎ",     romaji:"migi",    ico:"👉" },
    { id:"di3", cs:"rovně",      en:"straight",   ja:"まっすぐ", romaji:"massugu", ico:"⬆️" },
    { id:"di4", cs:"tady",       en:"here",       ja:"ここ",     romaji:"koko",    ico:"📍" },
    { id:"di5", cs:"tam",        en:"there",      ja:"あそこ",   romaji:"asoko",   ico:"🔭" },
    { id:"di6", cs:"blízko",     en:"near",       ja:"ちかい",   romaji:"chikai",  ico:"🟢" },
    { id:"di7", cs:"daleko",     en:"far",        ja:"とおい",   romaji:"tooi",    ico:"🔴" },
    { id:"di8", cs:"sever",      en:"north",      ja:"きた",     romaji:"kita",    ico:"🧭" },
    { id:"di9", cs:"jih",        en:"south",      ja:"みなみ",   romaji:"minami",  ico:"🧭" },
    { id:"di10",cs:"východ",     en:"east",       ja:"ひがし",   romaji:"higashi", ico:"🧭" },
    { id:"di11",cs:"západ",      en:"west",       ja:"にし",     romaji:"nishi",   ico:"🧭" },
    { id:"di12",cs:"před",       en:"in front",   ja:"まえ",     romaji:"mae",     ico:"⏩" },
    { id:"di13",cs:"za",         en:"behind",     ja:"うしろ",   romaji:"ushiro",  ico:"⏪" },
    { id:"di14",cs:"vedle",      en:"next to",    ja:"となり",   romaji:"tonari",  ico:"↔️" }
  ]},
  { id:"phrases", name:"Užitečné fráze", ico:"💬", color:"#6c5ce7", noType:true, words:[
    { id:"ph1",  cs:"jmenuji se",        en:"my name is",          ja:"わたしのなまえは",     romaji:"watashi no namae wa", ico:"🪪" },
    { id:"ph2",  cs:"nerozumím",         en:"I don't understand",  ja:"わかりません",         romaji:"wakarimasen",         ico:"🤔" },
    { id:"ph3",  cs:"mluv pomalu",       en:"speak slowly",        ja:"ゆっくりはなして",     romaji:"yukkuri hanashite",   ico:"🐢" },
    { id:"ph4",  cs:"pomoz mi",          en:"help me",             ja:"たすけて",             romaji:"tasukete",            ico:"🆘" },
    { id:"ph5",  cs:"omluv mě",          en:"excuse me",           ja:"すみません",           romaji:"sumimasen",           ico:"🙏" },
    { id:"ph6",  cs:"rád tě poznávám",   en:"nice to meet you",    ja:"はじめまして",         romaji:"hajimemashite",       ico:"🤝" },
    { id:"ph7",  cs:"na shledanou",      en:"see you later",       ja:"またね",               romaji:"mata ne",             ico:"👋" },
    { id:"ph8",  cs:"mám to rád",        en:"I like it",           ja:"すきです",             romaji:"suki desu",           ico:"👍" },
    { id:"ph9",  cs:"v pořádku",         en:"no problem",          ja:"だいじょうぶ",         romaji:"daijoubu",            ico:"🆗" },
    { id:"ph10", cs:"ještě jednou",      en:"once more",           ja:"もういちど",           romaji:"mou ichido",          ico:"🔁" },
    { id:"ph11", cs:"účet prosím",       en:"check please",        ja:"おかいけいおねがいします", romaji:"okaikei onegaishimasu", ico:"🧾" },
    { id:"ph12", cs:"kolik to stojí",    en:"how much is it",      ja:"いくらですか",         romaji:"ikura desu ka",       ico:"💰" },
    { id:"ph13", cs:"kde je záchod",     en:"where is the toilet", ja:"トイレはどこですか",   romaji:"toire wa doko desu ka", ico:"🚻" },
    { id:"ph14", cs:"mluvíš anglicky",   en:"do you speak English",ja:"えいごをはなせますか", romaji:"eigo wo hanasemasu ka", ico:"🗣️" }
  ]}
];

/* Plochý seznam všech slov s odkazem na jednotku */
const ALL_WORDS = [];
UNITS.forEach(u => u.words.forEach(w => { w.cat = u.id; w.unitName = u.name; ALL_WORDS.push(w); }));
const WORD_BY_ID = {};
ALL_WORDS.forEach(w => WORD_BY_ID[w.id] = w);

/* ---------- ÚSPĚCHY ---------- */
const ACHIEVEMENTS = [
  { id:"first",   ico:"🐣", name:"První krůček",     desc:"Dokonči svou první lekci",        goal:1,   track:"lessons" },
  { id:"l5",      ico:"🦅", name:"Na křídlech",      desc:"Dokonči 5 lekcí",                 goal:5,   track:"lessons" },
  { id:"l20",     ico:"🚀", name:"Raketa",           desc:"Dokonči 20 lekcí",                goal:20,  track:"lessons" },
  { id:"combo10", ico:"⚡", name:"Kombinátor",        desc:"Získej kombo 10 v lekci",         goal:10,  track:"maxCombo" },
  { id:"combo25", ico:"🌩️", name:"Bouřkový mozek",    desc:"Získej kombo 25 v lekci",         goal:25,  track:"maxCombo" },
  { id:"perfect", ico:"💎", name:"Bez chyby",        desc:"Dokonči lekci bez ztráty srdce",  goal:1,   track:"perfectLessons" },
  { id:"poly",    ico:"🌍", name:"Polyglot",         desc:"Uč se všechny 3 jazyky",          goal:3,   track:"langsTried" },
  { id:"s3",      ico:"🔥", name:"Denní ptáče",      desc:"3denní série",                    goal:3,   track:"bestStreak" },
  { id:"s7",      ico:"🏔️", name:"Týden v ohni",      desc:"7denní série",                    goal:7,   track:"bestStreak" },
  { id:"master20",ico:"🧠", name:"Mistr slovíček",   desc:"Zvládni 20 slov naplno",          goal:20,  track:"mastered" },
  { id:"xp100",   ico:"💯", name:"Stovkař",          desc:"Získej 100 XP",                   goal:100, track:"totalXp" },
  { id:"xp1000",  ico:"👑", name:"Legenda",          desc:"Získej 1000 XP",                  goal:1000,track:"totalXp" },
  { id:"online",  ico:"🌐", name:"Online hráč",      desc:"Synchronizuj skóre do žebříčku",  goal:1,   track:"lbSync" },
  { id:"speak10", ico:"🎤", name:"Výřečný",          desc:"Zvládni 10 výslovnostních otázek", goal:10, track:"speakCount" },
  { id:"listen10",ico:"🎧", name:"Krasoslech",       desc:"Zvládni 10 poslechových otázek",   goal:10, track:"listenCount" }
];

/* Názvy úrovní podle XP */
const LEVEL_NAMES = [
  "Nováček","Začátečník","Žák","Student","Znalec",
  "Polyglot","Mistr slov","Jazykový šampion","Guru","Legendární lingvista"
];